version: "3"

services:
  rabbitmq:
    image: rabbitmq:4
    container_name: rabbitmq
    restart: always
#    ports:
#      - 8080:5672
    networks:
      - app

  msg_api:
    build: ./src/msg_api/.
    container_name: msg_api
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
    networks:
      - app


  msg_worker:
    build: ./src/msg_worker/.
    container_name: msg_worker
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - rabbitmq
      - msg_api
    volumes:
      - ./.env:/app/.env
    networks:
      - app


networks:
  app:
    driver: bridge
